# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: João Almeida
email: joaorsalmeida@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Me chamo João Almeida e trabalho com desenvolvimento de software desde
  2006. Neste espaço vou compartilhar alguns atalhos para outros programandores
  e falar sobre meus projetos recentes como o Campus Code e o Code Saga.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://joaoalmeida.com.br" # the base hostname & protocol for your site
twitter_username: joaorsalmeida
github_username:  joaorsalmeida

# Build settings
markdown: kramdown
